version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: =my-password
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
      ADMINER_DEFAULT_DRIVER: pgsql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Changed port mapping to match the backend Dockerfile
    environment:
      - POSTGRES_SERVER=localhost
      - POSTGRES_PASSWORD=password
    env_file:
      - ./backend/.env
    depends_on:
      - postgresdb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Changed port mapping to match the frontend Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:80  # Changed to use port 80 of backend service
    restart: always

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  pgdata2:
