version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.genni.mooo.com`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
      ADMINER_DEFAULT_DRIVER: pgsql

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`genni.mooo.com`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    environment:
      - POSTGRES_SERVER=postgresdb
      - POSTGRES_PASSWORD=password
    env_file:
      - ./backend/.env
    depends_on:
      - postgresdb
    restart: always

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`genni.mooo.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend
    restart: always

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`proxy.genni.mooo.com`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DEFAULT_HOST: genni.mooo.com
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  pgdata2:
